### ISSUE TITLE
Is it possible to export to Android / IOS?

### ISSUE THREAD

**Issue by viniciusaportela** [francogarcia/GD-PDF#3]
Hi, I'm wondering if the PDF module just works in Desktop or if there is possible to use this module on mobile apps.

**Comment by francogarcia** [comment]
Hello, @viniciusaportela ,
How are you?

From the [documentation](<https://github.com/libharu/libharu/wiki/Installation>), it seems that libHaru only supports desktop platforms.
Therefore, the practical answer is no. It does not work for mobile out of the box.

The technical answer is probably -- with some work.
There seems to be ports of the library to [Android](<https://github.com/draekko-rand/libharu-android>) and to [iOS](<https://github.com/OpenSoftwareSolutions/libHaru>).
If they preserve the original API, they might work as drop-in replacements for the module.
However, you may have to make adjustments to Scons to compile the libraries.

Furthermore, please note that this module was written for Godot 2 and it has not been updated since.

Best regards,
Franco

**Comment by viniciusaportela** [comment]
Understood, thanks for the answer!
